### PR TITLE
EZS-867: Design improvement for the recommended articles

### PR DESCRIPTION
**Pull request by clash82**
https://jira.ez.no/browse/EZS-867

Preloader screen (old font):
screen shot 2016-08-24 at 12 20 53

Recommended articles (old font):
screen shot 2016-08-24 at 12 21 22

--

Updated font for the recommended articles label and cards titles:

screen shot 2016-08-25 at 11 28 28

### CODE REVIEW

**Comment by andrerom** [comment]
+1, nice :)

**Comment by lserwatka** [comment]
Nice, but this Times New Roman font does not fit at all, imho. Inconsistent with other main font on the page.

**Comment by clash82** [comment]
> +1, nice :)

Thanks :)

> Nice, but this Times New Roman font does not fit at all, imho. Inconsistent with other main font on the page.

Agree, but it was not my idea. It was like this on mockups.

Final approval required @SylvainGuittard

**Comment by andrerom** [comment]
> Agree, but it was not my idea. It was like this on mockups.

mockups are mockups, unless you refer to something made by designer and something to follow in details per pixel, I would assume they gladly agree to tweak the font to be consistent.

**Comment by SylvainGuittard** [comment]
+1. Good job @clash82 

> Nice, but this Times New Roman font does not fit at all, imho. Inconsistent with other main font on the page.

It should be "PT Serif", a font we are already using on the demo.
The idea is to create a zone that the user can easily identify. Maybe @inakijv can provide more details.

**Comment by inakijv** [comment]
It looks great. 
As Sylvain says, the font is "PT Serif".

**Comment by clash82** [comment]
It's "PT Serif"!

screen shot 2016-08-24 at 15 17 31

;-)

**Comment by lserwatka** [comment]
Why do you use Serif font while over the place is non-serif font? :)

**Comment by esteban-xrow** [comment]
I prefer non-serif for titles and serif for reading/articles... :-D

**Comment by inakijv** [comment]
We combine sans-serif and serif fonts, to make it easy to the user to scan and read the page. Besides, for a large amount of text it's easier to read a serif font. :-)

**Comment by lserwatka** [comment]
But we have only titles here, not so much text from recommendation items, thus this should be non-serif, following your thinking :)

**Comment by SylvainGuittard** [comment]
Thanks for the review guys!

Here is my suggestion:
72dcbc8e-69fa-11e6-8fe6-927fc43a9718
To be more consistent, I suggest to reuse the same design (fonts, colors,...) we have in the top menu.

- "Recommended Articles" should be like "our latest article"
- titles of the cards should be like "Ethiopian Cuisine" 

What do you think?

**Comment by inakijv** [comment]
I have reviewed the patterns and your suggestion makes sense. I am more up to highlighting the difference (that was the reason for me to go for the PT Serif), but it will be more consistent.

**Comment by SylvainGuittard** [comment]
@clash82 could you please update the PR?

**Comment by clash82** [comment]
@SylvainGuittard updated (screenshot attached in the task description).

**Comment by SylvainGuittard** [comment]
Thanks @clash82 
+1

**Pull request merged**
